bin/vmrss: switch to zsh+ps implementation instead of bash+/proc to make it work on macOS
https://github.com/ThePrimeagen/vmrss/issues/6

diff --git a/bin/vmrss b/bin/vmrss
--- a/bin/vmrss
+++ b/bin/vmrss
@@ -1,72 +1,49 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh
 
 # Print the Virtual Memory Resident Set Size (physical memory used) of a pid and all processes it spawned.
-# From https://github.com/ThePrimeagen/vmrss; added fzf for PID selection
+# From https://github.com/ThePrimeagen/vmrss/issues/6 since original didn't work on macOS since it relied on /proc
 # Details about types of memory: https://poby.medium.com/linux-memory-demystified-eb33e81699b2
 
-# if [ $# -eq 0 ]; then
-#     echo "Usage: $0 <pid>"
-#     exit 1
-# fi
+# enable pid completion, e.g. `vmrss nvim<TAB>`, needs to be put in .zshrc
+# compdef _pids vmrss
 
-function print_vmrss() {
-    declare -a arr
-    arr=("$1" 0)
-    total=0
+if [[ $# -eq 0 ]]; then
+    echo "usage: ${0:t} <pidlist>"
+    exit 1
+fi
 
-    while [ ${#arr[@]} -gt 0 ]; do
+if ! kill -0 "$@" &>/dev/null; then
+    echo "error: invalid process ID(s)"
+    exit 1
+fi
 
-        # remove last element
-        space=${arr[${#arr[@]}-1]}
-        unset arr[${#arr[@]}-1]
-        pid=${arr[${#arr[@]}-1]}
-        unset arr[${#arr[@]}-1]
-
-        [ -d "/proc/$pid" ] || continue
-
-        GREP_OPTS=${GREP_OPTS:-"
-          --color=auto
-          --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}
-          "}
-        mem=$(grep $GREP_OPTS VmRSS /proc/$pid/status \
-          | grep $GREP_OPTS -o '[0-9]\+' \
-          | awk '{print $1/1024}')
-        #Add decimals to total
-        total=$(echo $mem+$total | bc)
-
-        # name of process
-        name=$(ps -p $pid -o comm=)
-
-        printf "%${space}s%s($pid): $mem MB\n" '' "$name"
-
-        # get children
-        children=$(pgrep -P $pid)
-
-        # add children to array
-        for child in $children; do
-            arr+=("$child" $((space+2)))
-        done
-    done
-    printf "Total: $total MB\n"
+# $1= pid
+print_vmrss() {
+    res=(${(s: :):-$(ps -p $1 -o pid=,rss=,comm=)})
+    res[2]=$((res[2] / 1024.0))
+    printf '%s(%s): %s MB\n' "${res[3,-1]:-}" ${res[1]:-$1} ${res[2]:-0}
+    REPLY=res[2]
 }
 
-# check VMRSS_MONITOR = 1
-if [ ! -z "$VMRSS_MONITOR" ]; then
-    while true; do
-        if ps -p $1 > /dev/null
-        then
-            print_vmrss $1
-            sleep 0.5
-        else
-            break
-        fi
+# $1= idx
+print_spc() {
+    printf "${(l:$(($1*2)):: :)}"
+}
+
+# $1= idx, $2=pid
+run() {
+    print_spc $1
+    print_vmrss $2
+    total=$((total + REPLY))
+    for child in $(pgrep -P $2); do
+        run $(($1+1)) $child
     done
-    print_vmrss $1
-elif [ $# -eq 0 ]; then
-    ps=$(ps -ef | fzf)
-    pid=$(echo "$ps" | awk '{print $2}')
-    echo "Selected process: $ps"
-    print_vmrss $pid
-else
-    print_vmrss $1
-fi
+}
+
+idx=0
+total=0
+pids=("$@")
+for pid in $pids; do
+    run $idx $pid
+done
+printf 'total: %s MB\n' $total
